name: scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/deepfactor/df/runtime:3.3.3-2346
      env:
        DF_RUN_TOKEN: ${{ secrets.DF_RUN_TOKEN }}
    steps:
    - name: Scan with Deepfactor
      run: dfctl scan -s fs -a deepfactor-experiment -c hello-world-github -V 0.0.1 .
